[package]
name = "glue"
version = "0.1.0"
authors = ["Nabeel Omer <nabeelkomer@gmail.com>"]
edition = "2018"

build = "build.rs"
links = "ruby"

[dependencies]
glue_macro = { path = "../glue_macro" }
proc-macro-hack = "0.5.2"
libc = "0.2"
